# Generated by Django 5.2.1 on 2025-05-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterBack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='posts_made',
            field=models.IntegerField(default=0),
        ),
    ]
