# Generated by Django 5.2.1 on 2025-05-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterBack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
