# Generated by Django 5.2.1 on 2025-05-16 02:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterBack', '0002_profile_posts_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='replies_liked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
    ]
