# Generated by Django 5.2.1 on 2025-05-16 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterBack', '0003_profile_replies_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='reply_edited',
        ),
    ]
