# Generated by Django 5.2.1 on 2025-05-16 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterBack', '0004_remove_reply_attachment_remove_reply_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
